mod_id=guiapi
mod_version=1.0.0
mod_name=GUI API
mod_description=Datapack GUI Framework

author=ToolkitMC

website=https://github.com/ToolkitMC/guiAPI
issues=https://github.com/ToolkitMC/guiAPI/issues
source_code=https://github.com/ToolkitMC/guiAPI

icon=assets/guiapi/icon.png
custom_provide=guiapi-api

minecraft_version=1.21.8
fabric_api_version=0.135.0+1.21.8
java_version=21
loader_version=0.17.3

main_entrypoint=GuiApi
client_entrypoint=GuiApiClient
server_entrypoint=GuiApiServer
modmenu_entrypoint=GuiApiModMenu
custom_entrypoint=GuiApiCustom
